### PR TITLE
adds waste calculator

### LINKED ISSUE #95: Write functions to calculate the waste produced by an energy source
This issue can be closed when a python file with functions to calculate the waste produced by an energy source has been produced. Along with documentation about information sources.

E.g. How much solar panel waste will there be (in tons) by 2050?
- The total volume/mass
- The constituents of that waste
- How much waste is produced per MWh of generation

### PR DESCRIPTION
**Pull request by samgdotson**
This PR adds a notebook that estimates how much waste is produced by each source on a per, MWh basis.

Closes #95

### CODE REVIEW

**Comment by samgdotson** [comment]
Output: 
Nuclear plants will produce approximately 0.0008154097619374136 kg/MWh(th) of spent nuclear fuel.
Railsplitter Wind Farm will produce 0.21037181996086105 kg/MWh of turbine waste
UIUC Solar Farm 1.0 will produce 2.046181362656811 kg/MWh of solar panel waste

**Comment by robfairh** [comment]
The issue says that you will include information about the constituents of the waste. I don't see that info in the notebook. Other than that, it looks good.

**Comment by samgdotson** [comment]
Yeah, I think the constituents of the waste is beyond the scope of this project for now. It doesn't make sense to try and document each kind of material for each kind of waste, it's losing the plot a little bit.
If it looks good, you can smash the merge button

**Review by robfairh — APPROVED** [review]
looks good

**Comment by samgdotson** [comment]
Thanks!

**Pull request merged**
