### PR TITLE
Devel: RAVEN input file produces physical synthetic histories

### LINKED ISSUE #13: Produce a synthetic history for solar power
This issue can be closed when a synthetic history is produced that 
- [ ] has the same statistics as a typical history
- [ ] reflects physical reality 

It is possible that
1. This data should not be modeled using an ARMA 
2. More parameters are needed to capture the correct behavior 
3. Another method of generating these series should be devised

### PR DESCRIPTION
**Pull request by samgdotson**
Closes #13 by adding a solar power synthetic history

### CODE REVIEW

**Review by gwenchee — CHANGES_REQUESTED** [review]
Looks good! 

A couple of comments on the notebook
1. you left one commented print statement in the step 2 section. Delete it? 
2. Why did you print `!ls ~/Research/data/`? It seems really messy to have it in the notebook. 

Also for your figures, perhaps you should add gridlines and limit both axes to start at 0. It just looks cleaner.

**Comment by samgdotson** [comment]
@gwenchee we can agree to disagree on the plots

**Comment by katyhuff** [comment]
> @gwenchee we can agree to disagree on the plots.

Actually, I agree with @gwenchee regarding starting at 0.
So, let's agree to agree, shall we?

(Though, I'm impartial regarding gridlines.)

**Comment by samgdotson** [comment]
Is this what you want?

image

**Comment by katyhuff** [comment]
bitmoji

**Pull request merged**
