### PR TITLE
Devel : Wind speed data analysis 

### PR DESCRIPTION
**Pull request by samgdotson**
Adds a jupyter notebook that analyzes the wind speed data from Lincoln Airport. 

Data functions are tested in /tests/

input files are used to run a RAVEN simulations.

Work is still ongoing for making data available to everyone.

### CODE REVIEW

**Review by robfairh — APPROVED** [review]

**Review by robfairh — CHANGES_REQUESTED** [review]
Can you add a little bit of more detail in the Jupyter notebook of how to access the data? By reading it I don't completely understand how to retrieve the files. There is also a line where you call the id of the file, where did you get that number from?

**Comment by robfairh** [comment]
The rest of the file and the other files look good!

**Comment by samgdotson** [comment]
I will add instructions to the ``README``. 

The data can be downloaded from a shared link in a Box folder.

**Review by robfairh — APPROVED** [review]

**Comment by robfairh** [comment]
LGTM!

**Pull request merged**
