### PR TITLE
EIA Hospital Market Analysis

### LINKED ISSUE #77: Add hospital data to the EIA analysis
This issue can be closed when a PR is merged that does the following:

- [x] Adds hospital data to the EIA market analysis functions
- [x] Creates an `ipynb` that displays graphs of the data similar to the `education_market_analysis.ipynb`
- [x] Updates test functions to match

### PR DESCRIPTION
**Pull request by datw0258**
Updated the `eia.py` and associated `education_market_analysis.ipynb` and tests to reflect adding the medical sector. Also added a `.ipynb` to show the medical data.

### CODE REVIEW

**Review by samgdotson — CHANGES_REQUESTED** [review]
This seems stable. All tests pass. In the notebooks you use the _absolute_ path ``C:\\Users\\Atwater\\research\\data\\``. It is better to use ``C:/Users/Atwater/research/data/``, forward slashes. Even better than that is to use a _relative_ path like:

``../../data/`` which tells the computer ``data_processing/pride/research/data``. This allows others to simply download the data to a ``data`` folder and then run your notebook without changing anything.

**Review by samgdotson — CHANGES_REQUESTED** [review]
Thanks for making the changes to the relative path, there are a couple of other things that need to be addressed, however. 

The notebooks will never run on a Unix machine, as written. 
Why is that?
   - Whenever a file is saved on a Windows machine, it is written with _DOS line endings_ (Windows = DOS machine). What looks like "Reported Primary Mover" on Windows looks like "Reported Primary\n Mover" on a Linux/Unix machine. So any Windows machine will be able to read it because it ignores the '\n' but a Unix machine will not. 
   - There are a couple of solutions. Change the column names in `eia.py` to reflect the DOS line endings (it should be okay in Windows too). The better solution is to use column *numbers* rather than the names themselves. You can figure out the column numbers by doing (this will print a number and column name pair)
```python
df = pd.read_csv(filename)
for key in enumerate(df.keys()):
    print(key)
```
Then, you will be able to read a csv file as 
```python
df = pd.read_csv(filename, header=5, usecols=[4, 8, 10])
```
Word of caution: These column numbers refer to the number in the spreadsheet. When manipulating the dataframe, the column numbers will be different. As long as the order is consistent that should be okay. The column numbers are superior to the names because it will run on any machine. 

Finally, thoughts:
- Windows can read Unix line endings, but not the other way around. That is, Unix can read them but they will always include something like "\r\n" when there's a line break. 
- Shorter column names will fix this too (but you'd have to go into the files themselves and change it, which is tedious and unnecessary). If you find yourself writing a dataframe to export, use short column names.
- If you need to write an input file for SERPENT, you should use
```python
with open(file, 'wb') as file:
[...]
```
because 'wb' means "write to binary" which will be read as unix line endings.

**Comment by samgdotson** [comment]
To be clear: I am asking you to change the ``pd.read_csv(usecols=['column1', 'column2']`` to ``pd.read_csv(usecols=[1, 2])``.

To save you some time, the column numbers are this:

``usecols=[4, 8, 10, 13, 14, 95]``

**Comment by datw0258** [comment]
> Thanks for making the changes to the relative path, there are a couple of other things that need to be addressed, however.
> 
> The notebooks will never run on a Unix machine, as written.
> Why is that?
> 
> * Whenever a file is saved on a Windows machine, it is written with _DOS line endings_ (Windows = DOS machine). What looks like "Reported Primary Mover" on Windows looks like "Reported Primary\n Mover" on a Linux/Unix machine. So any Windows machine will be able to read it because it ignores the '\n' but a Unix machine will not.
> * There are a couple of solutions. Change the column names in `eia.py` to reflect the DOS line endings (it should be okay in Windows too). The better solution is to use column _numbers_ rather than the names themselves. You can figure out the column numbers by doing (this will print a number and column name pair)
> 
> ```python
> df = pd.read_csv(filename)
> for key in enumerate(df.keys()):
>     print(key)
> ```
> 
> Then, you will be able to read a csv file as
> 
> ```python
> df = pd.read_csv(filename, header=5, usecols=[4, 8, 10])
> ```
> 
> Word of caution: These column numbers refer to the number in the spreadsheet. When manipulating the dataframe, the column numbers will be different. As long as the order is consistent that should be okay. The column numbers are superior to the names because it will run on any machine.
> 
> Finally, thoughts:
> 
> * Windows can read Unix line endings, but not the other way around. That is, Unix can read them but they will always include something like "\r\n" when there's a line break.
> * Shorter column names will fix this too (but you'd have to go into the files themselves and change it, which is tedious and unnecessary). If you find yourself writing a dataframe to export, use short column names.
> * If you need to write an input file for SERPENT, you should use
> 
> ```python
> with open(file, 'wb') as file:
> [...]
> ```
> 
> because 'wb' means "write to binary" which will be read as unix line endings.

I believe I fixed this issue by changing the .csv files in the box to remove the \n. Is this a separate issue?

**Comment by samgdotson** [comment]
I downloaded the files in box today and the issue remains. 

Edit: It looks like you changed it for only 2018, since you reference other files those also need to be changed.

**Review by samgdotson — APPROVED** [review]
All the tests pass and I can now run the notebooks with ease.

I will merge this but I want to make a quick note:
There is no reason to throw an error if the parameter "year" is not the type "str" because you 
can force the year to be a string by just typecasting with ``str(year)``. If it's already a string, nothing bad happens. A trivial detail.

Thanks for making all these changes @datw0258 !

**Pull request merged**
