### PR TITLE
Iss29: adds rail splitter data analysis

### LINKED ISSUE #29: Analyze data from Rail Splitter
Recently received actual wind power data from Mike Marquissee. 
This issue can be closed when that data has been analyzed and a typical and series of synthetic histories have been generated.

### PR DESCRIPTION
**Pull request by samgdotson**
Closes #29 by adding typical and synthetic histories and RAVEN input files for rail splitter wind power.

### CODE REVIEW

**Review by robfairh — COMMENTED** [review]
What is 'Rail Splitter'?

**Review by robfairh — APPROVED** [review]
Looks good

**Comment by samgdotson** [comment]
Roberto can you merge it...?

**Comment by robfairh** [comment]
yes

**Pull request merged**
