### PR TITLE
Adds geothermal technology to TEMOA's model

### PR DESCRIPTION
**Pull request by robfairh**
This PR addresses #132 by adding a geothermal technology ```GEOT``` to the model.

Here is the figure of the new model:
11_uiuc

@yardasol let me know if you have already created a scenario 11, if that's the case, this PR will hinder your work.
In that case, I will postpone this PR for later.

@samgdotson a few things:
* ```GEOT``` converts ```ELC``` to ```USTM```, should the ```MinActivity``` be in electric or thermal GWh?
* Same question for ```CapacityToActivity``` and ```ExisistingCapacity```.
* snakemake runs and produces several figures. To see the GEOT generation I added ```GEOT``` to ```ind_techs```. And this is the result:

scenario11_ind_generation

I guess I should add an entry in the table ```MaxActivity```.
* Does the sector in the table ```technologies``` matter? I set the sector of ```GEOT``` to be ```electric```. Should it be ```industrial```?

### CODE REVIEW

**Comment by robfairh** [comment]
Interestingly, this PR doesn't let me put @samgdotson as a reviewer. Other PRs let me, but this one doesn't. I am confused.
I believe @samgdotson you can still review this PR.

**Comment by yardasol** [comment]
> @yardasol let me know if you have already created a scenario 11, if that's the case, this PR will hinder your work.
> In that case, I will postpone this PR for later.

I have started a scenario 11 .sql file and am filling in the fixed cost table.

**Comment by samgdotson** [comment]
It's very odd that I can't be added as a reviewer. 
Some other thoughts: 
1) Land use requirements (area per unit capacity)
2) Fixed Costs
3) Investment costs
4) variable cost (zero because it uses electricity produced on campus). 

Also, we don't want to artificially limit or force Temoa to do certain things. We aren't trying to evaluate the proposed iCAP transitions, but rather determining what an ideal transition would look like.

**Comment by robfairh** [comment]
I added ```CostInvest```,  ```CostFixed```, and ```LandUse``` calculations to a jupyter notebook.
I am not sure about the following:
* ```CostFixed```: The original formula includes the labor cost of operating the plant. I think we should be careful about that. If @yardasol included that in his numbers, then we should consider it, and if he didn't, then we shouldn't. I am not sure if we should consider it anyway, cause I am assuming that all the plants probably have more or less the same labor cost. So if UIUC deploys a geothermal plant or something else, the cost won't change considerably. It makes sense in my head. What do you think @samgdotson?
* ```LandUse```: First, the geothermal plant has a land-use requirement associated with the plants and also the well-field where the boreholes are. However, the boreholes are located under the ground. How far underground, I am not sure. So I don't know if it limits the construction of buildings or not above them. Maybe I should look into that a bit more. If it is possible to construct above the well-field, then I wouldn't consider that land-use requirement. If it is not possible to construct anything above the well-field, then I should consider those numbers. The current numbers in the Jupyter notebook don't consider the land-use requirement of the boreholes. Second, Temoa doesn't have any tables for the land-use requirements, is that the contribution you were talking about @samgdotson?

**Comment by robfairh** [comment]
About the ``` LandUse ```, BSU built above the boreholes recreational fields and parking lots, which means that the surface area above the boreholes is usable after their installation. I can include them in the calculations anyway so we have a more conservative estimation.

**Comment by samgdotson** [comment]
> About the `LandUse`, BSU built above the boreholes recreational fields and parking lots, which means that the surface area above the boreholes is usable after their installation. I can include them in the calculations anyway so we have a more conservative estimation.

Temoa does not have specific tables for land requirements. Land use is an interesting but difficult thing to make sharp statements about because, like you mention, it might have multiple uses. The land above the boreholes might be used for crops, solar panels can be raised to allow for farming as well. Wind turbines have a similar story. We are simply reporting the amount of land that is required for each energy source -- not remarking on all of the possible uses for this land. Does that make sense?

@yardasol should indicate what is being counted in the fixed cost. I agree that we need to be consistent across all energy sources.

**Comment by robfairh** [comment]
> Temoa does not have specific tables for land requirements. Land use is an interesting but difficult thing to make sharp statements about because, like you mention, it might have multiple uses. The land above the boreholes might be used for crops, solar panels can be raised to allow for farming as well. Wind turbines have a similar story. We are simply reporting the amount of land that is required for each energy source -- not remarking on all of the possible uses for this land. Does that make sense?

Yes!

**Comment by robfairh** [comment]
@samgdotson I realized I forgot to mention that the current model only uses the geothermal plant for producing steam.
However, an additional benefit from geothermal heat pumps is that they produce chilled water as well.
I haven't included that in the model.
If I did that, we would need to add a CHW commodity and change the CHWS. And somehow translate CHW into electricity. We can talk about this in our meeting today (01/12/21).

**Comment by samgdotson** [comment]
Can we turn this into a ``TechOutputSplit``? 
1 unit of electricity turns into 1 unit of steam and 0.2 units of electricity. (for example, I just made these numbers up) This needs to be accounted for in the ``Efficiency`` table. I.e. an efficiency for elc --> geoth --> elc and elc --> geoth --> steam.

Then we have to explain that this electricity feedback is actually due to chilled water storage and "load shift."

**Comment by robfairh** [comment]
Here is the diagram of the latest model.

11_uiuc

The geothermal plant produces both ```USTM``` and ```ELC```.

**Comment by robfairh** [comment]
I have the following concern. ```GEOT``` input is ```ELC```. ```GEOT``` has two outputs: ```USTM``` and ```ELC```. So far, so good.
Now, the outputs have different units.
Normally the capacity is calculated with the output capacity of the technology.
In this case, there would be two output capacities, one for heating (produces ```USTM```) and one for cooling (produces ```ELC```).
How should the capacity be calculated in this case?
I think it would be easier to model ```GEOT``` separated into two technologies, one for heating and one for cooling.
However, the O&M cost associated with the plant is one, and it is not separated by function.
What do you think @samgdotson?

**Comment by robfairh** [comment]
Here is the diagram of the latest model:

11_uiuc

And here is a figure with one of the results:

scenario11_ind_generation

In the file ``` geothermal.ipynb ``` I state some of the assumptions.
This is what I wrote down for the geothermal plant (what we discussed IRL yesterday), let me know what you think @samgdotson:

Having one technology with two outputs using different forms of energy complicates the model. The cooling section of the plant produces savings in electricity consumption. By subtracting those savings from the plant's electricity inlet, we virtually increase the efficiency of the heating section of the plant. This way, we only model the geothermal plant as a heating plant with a virtually higher efficiency.

**Comment by robfairh** [comment]
These new results consider what Olek added in the model (the investment and fixed costs):

elc generation:
scenario11_elc_generation

ind generation:
scenario11_ind_generation

vcl generation:
scenario11_vcl_generation


@samgdotson @yardasol this is ready to be reviewed.

**Review by samgdotson — APPROVED** [review]
This looks great. There results are still a bit strange but we can investigate more later.

**Pull request merged**
